create table if not exists public.usage_logs (
  id bigint generated by default as identity primary key,
  user_id text not null,
  tokens_used integer not null default 0,
  created_at timestamptz not null default now()
);

create index if not exists usage_logs_user_created_at_idx on public.usage_logs (user_id, created_at desc);
